; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.3.0
; TUNING_UART_V204.inc
; 05:09:45 PM Monday, December 23, 2019
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "TUNING_UART_20161019.mcu" 
#include "..\BS66F360_LIBV413\BS66F360_LIBV413.aex" 
#include "..\MAIN_PROGRAM_V104\MAIN_PROGRAM_V104.aex" 
#include "..\USER_PROGRAM\USER_PROGRAM.aex" 

#define _TUNING_UART_V204_ 
