/*************************************************************************************************************************
 * Created by: Holtek Touch MCU Workshop, Version 3.5.3.0
 * TKS_GLOBE_VARIES.H
 * 09:30:31 AM Tuesday, December 24, 2019
*************************************************************************************************************************/
#include <BS66F360.h>
#define _BS66F360_
#define _V413_
#define SystemClock     2
// Components' settings ...
