; ========================================================================================================================
; * Created by: Holtek Touch MCU Workshop, Version 3.5.3.0
; USER_PROGRAM.inc
; 09:30:31 AM Tuesday, December 24, 2019
; ========================================================================================================================
#include "..\TKS_GLOBE_VARIES.inc" 
#include "..\BS66F360_LIBV413\BS66F360_LIBV413.aex" 
#include "..\MAIN_PROGRAM_V104\MAIN_PROGRAM_V104.aex" 
